---
title: "Statistical Data"
listing: graphs
---

```{r packages, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
library(tidyverse)
library(readxl)
library(ggplot2)
```

## Mortality Rate
```{r mortality rate with ggplot and geom line with discrete variables}
library(readxl)
# install.packages("viridis")
library(viridis)
# install.packages("scales")
library(scales)
Pivot_Vaccination <- read_excel("Pivot_Vaccination.xlsx")
 ggplot(Pivot_Vaccination, aes(x=Month_of_Death, y=Death_Count, group=Country, color=Country)) +
    geom_line() +
    scale_y_continuous(label = label_number_si()) +
    scale_color_viridis(discrete = TRUE) +
    ggtitle("Covid Mortality Rate") +
    labs(y= "Number of Deaths", x="Month")
```


## Average Years of Schooling per Continent

```{r average education in years in different continents and reading in data from excel file}
Average_years_of_education2 <- read_excel("Average_years_of _education2.xlsx")
ggplot() +
  geom_col(Average_years_of_education2, 
       mapping= aes(x = Continent, y = Year_of_2020 ,  fill= Continent))+ ggtitle ("Average years of education for each Continent") + labs(y= "Average Years of Education Provided")
```


## Stem Majors
```{r stem majors 2020 by country}
stem_majors_2020_by_country <- read_excel("stem majors 2020- by country.xlsx")
ggplot() +
  geom_point(stem_majors_2020_by_country, 
       mapping= aes(x = Country_stem, y = Share_of_Graduates, color = Country_stem )) + ggtitle("Share of Graduates in STEM field in each Country") +labs(x="Country", y= "Share of Graduates in stem field")
```

```{r stem}
stem_majors_2020_by_country <- read_excel("stem majors 2020- by country.xlsx")
ggplot() +
  geom_point(stem_majors_2020_by_country, 
       mapping= aes(x = Country_stem, y = Total_Graduates, color=Country_stem )) + scale_y_continuous(label = label_number_si())+ ggtitle("Number of total Graduates in STEM from each pertaining Country") + labs(x="Country", y="Total Number of STEM graduates")
```

## Income Support
```{r}
income_mask_sah <- read_excel("income_mask_sah.xlsx")
ggplot() +
  geom_point(income_mask_sah, 
       mapping= aes(x = Country, y = Amount_of_Income_Support, color=Country))+ labs(y="Amount of Income support (<50%, >50%, or NONE)")
```


## Stay at Home Requirements
```{r stay at home requirements (exclude NA) }
income_mask_sah <- read_excel("income_mask_sah.xlsx")
ggplot() +
  geom_point(income_mask_sah, 
       mapping= aes(x = Country, y = Stay_at_home_requirements, color= Stay_at_home_requirements)) + labs(y= "Stay at home requirements")
```


## Vaccination Data

```{r vaccination percentages as a stacked bar graph}
library(readxl)
Vaccination_percentages <- read_excel("Vaccination_percentages.xlsx")

p<-ggplot(Vaccination_percentages, aes(x= Continent,
                                       y= Rate,
                                       fill= Percentage_Type
))
p +
   geom_bar(stat = "identity", 
            width = 0.6,      
            color = "black",  
            size = 0.5,         
            alpha = 0.7) +    
   theme_minimal()+           
   theme(legend.position = "right", axis.text.x = element_text(angle = 45, hjust = 0.8)) +                         
   labs(x= "Continent", y = "Rate", title = "Percentages of Continents Vaccinated as of Nov. 1st",
        caption = "ourworld.org data")+  
   geom_text(aes(label = Rate), position = position_stack(vjust = 0.5), size = 3) + labs(y="Percent Fully/Partially Vaccinated")
 
```


## Face Covering Policies
```{r}
income_mask_sah <- read_excel("income_mask_sah.xlsx")
ggplot() +
  geom_point(income_mask_sah, 
       mapping= aes(x = Mask_Mandates, y = Country, color= Mask_Mandates)) + labs(y= "Mask Requirements", )
```


## Poverty Rate
```{r}
povertyrate <- read_excel("povertyrate.xlsx")
ggplot() +
  geom_point(povertyrate, 
       mapping= aes(x = Pov_rate, y = Continents))
```

